import pathlib,json,hashlib,math,sqlite3,shapely
from shapely.geometry import Polygon,box,mapping
from shapely.ops import transform,polylabel
R=pathlib.Path.cwd();B=R/'data/model-source/bespoke';P=B/'acro-riverview-102-105-family';P.mkdir(exist_ok=True);O=B/'acro-riverview-101-representative';src=B/'acro-riverview-research/root-reviewed-source-101-105.json';assert hashlib.sha256(src.read_bytes()).hexdigest()=='1d0a4f420d72a16bf5c82e4e8aeede8ab56930be7882809eb324fdb3a776f7aa';A=json.loads(src.read_text());db=sqlite3.connect(R/'data/model-source/residential-survey/register.sqlite');db.row_factory=sqlite3.Row
for t in range(102,106):
 p=P/str(t);p.mkdir(exist_ok=True);e=next(x for x in A['entries'] if x['tower']==str(t)+'동');b=e['osm_building'];reg=dict(db.execute('select * from reg where id=?',(e['register']['id'],)).fetchone());assert reg==e['register'];g=json.loads(b['geometry']);outer=g['coordinates'][0][:-1];lon=sum(x for x,y in outer)/len(outer);lat=sum(y for x,y in outer)/len(outer);rings=[[[ (x-lon)*111320*math.cos(math.radians(lat)),(y-lat)*111320] for x,y in ring[:-1]] for ring in g['coordinates']];r=rings[0];poly=Polygon(r,rings[1:]);edge=max(zip(r,r[1:]+r[:1]),key=lambda q:math.dist(*q));theta=math.atan2(edge[1][1]-edge[0][1],edge[1][0]-edge[0][0]);co,si=math.cos(theta),math.sin(theta);uv=transform(lambda x,y:(x*co+y*si,-x*si+y*co),poly);c=polylabel(uv,tolerance=.01);w,h=10.,5.
 while not uv.buffer(-.25).covers(box(c.x-w/2-.2,c.y-h/2-.2,c.x+w/2+.2,c.y+h/2+.2)):w*=.95;h*=.95
 H=float(reg['height']);F=int(reg['floors']);d={'tower':str(t),'approved_entry':e,'id':b['id'],'geometry':g,'ring_m':r,'rings_m':rings,'anchor_lonlat':[lon,lat],'register_row':reg,'register_height_m':H,'floors':F,'osm_height_m':b['height_m'],'facade_axis_rad_inferred':theta,'roof_cap_uv':[c.x,c.y,w,h],'body_height_m':H-1.25,'roof_deck_height_m':H-1.,'model_upper_envelope_m':H,'reference_scope':'Representative-photo-inference from root-approved Acro Riverview101; listing-card photo, not resident-review attribution; numbered image and orientation unknown','height_assumption':f'No source child parts; uniform own full source footprint envelope{H}m. Roof cap dimensions and legal roof datum unconfirmed.','source_sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'photo_sha256':'16ab5a8f40bc47498ba8149cb75d33371bfe42f924af4fcfcdc99ae1b6e0b86f','inferredFromAssetIds':['bespoke-acro-riverview-101'],'ancestor_glb_sha256':'576bf05fbc20169bfd459ac65351c202809b794a74e83c478aaf4fa0d5317ed2','supersedesAssetIds':None,'proposedSupersedesAssetIds':['fallback-acro-riverview-'+str(t)],'binding_status':'pending root verified compound splits','current_owner_asset_ids':[]};(p/'source-data.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(p/'regions.json').write_text(json.dumps([{'id':'uniform-parent-assumption','geometry':mapping(poly),'height_m':H,'body_height_m':H-1.25,'roof_deck_height_m':H-1.,'floors':F,'basis':d['height_assumption'],'triangles':[list(q.exterior.coords)[:3] for q in shapely.constrained_delaunay_triangles(poly).geoms]}],indent=2))
 s=(O/'build.py').read_text().replace('ARV101','ARV'+str(t)).replace('Shinbanpo101','Shinbanpo'+str(t)).replace('acro-riverview-101','acro-riverview-'+str(t)).replace("'register_height_m':93.55","'register_height_m':D['register_height_m']").replace("'model_upper_envelope_m':93.55","'model_upper_envelope_m':D['register_height_m']").replace("'floors':31","'floors':D['floors']").replace('H=93.55;body=92.30;FLOORS=31',"H=D['register_height_m'];body=H-1.25;FLOORS=D['floors']").replace('92.55','(H-1.)').replace('92.95','(H-.60)').replace('93.40','(H-.15)');s=s.replace('batches={}\n',"s['inferredFromAssetIds']=json.dumps(D['inferredFromAssetIds']);s['ancestor_glb_sha256']=D['ancestor_glb_sha256']\nbatches={}\n");(p/'build.py').write_text(s)
 s=(O/'check-standalone.py').read_text().replace('acro-riverview-101','acro-riverview-'+str(t)).replace("r['floors']==31","r['floors']==D['floors']").replace("r['height_m']==93.55","r['height_m']==D['register_height_m']").replace('-93.55)',"-D['register_height_m'])");(p/'check-standalone.py').write_text(s)
 s=(O/'validate.py').read_text().replace("P=R/'data/model-source/bespoke/acro-riverview-101-representative'","P=pathlib.Path(__file__).parent").replace("P.parent/'acro-riverview-research","P.parent.parent/'acro-riverview-research").replace("=='101동'","=='"+str(t)+"동'").replace('acro-riverview-101.glb','acro-riverview-'+str(t)+'.glb').replace("('roof',92.55)","('roof',D['roof_deck_height_m'])").replace('-93.55)',"-D['register_height_m'])").replace('>92.5501',">D['roof_deck_height_m']+.0001").replace("'floors':31","'floors':D['floors']").replace("'height_m':93.55","'height_m':D['register_height_m']").replace("'roof_deck_height_m':92.55","'roof_deck_height_m':D['roof_deck_height_m']");(p/'validate.py').write_text(s);print(t,H,F)
for i,start in enumerate([102,104],1):(P/f'batch-{i}.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in range("+str(start)+","+str(start+2)+"):\n p=P/str(t)/'build.py';exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'check-all.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in range(102,106):\n p=P/str(t)/'check-standalone.py';exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'prior-hashes.json').write_text(json.dumps({str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in O.rglob('*') if p.is_file()},indent=2))
