import pathlib,json,hashlib,math,shapely,sqlite3
from shapely.geometry import Polygon,box,mapping
from shapely.ops import transform,polylabel
R=pathlib.Path.cwd();B=R/'data/model-source/bespoke';P=B/'shinbanpo-xi-102-107-family';P.mkdir(exist_ok=True);O=B/'shinbanpo-xi-101-representative';A=json.loads((B/'shinbanpo-xi-research/root-reviewed-source-101-107.json').read_text());bind=json.loads((R/'docs/model-audit/shinbanpo-xi-fallback-bindings.json').read_text());db=sqlite3.connect(R/'data/model-source/residential-survey/register.sqlite');db.row_factory=sqlite3.Row
for t in range(102,108):
 p=P/str(t);p.mkdir(exist_ok=True);e=next(x for x in A['entries'] if x['tower']==str(t)+'동');d=json.loads((B/'shinbanpo-xi-family-prep'/str(t)/'source-data.json').read_text());reg=dict(db.execute('select * from reg where id=?',(e['register']['id'],)).fetchone());assert reg==e['register']==d['register_row'];binding=next(x for x in bind['bindings'] if x['number']==t);assert binding['sourceFootprintId']==d['id'];r=d['rings_m'][0];poly=Polygon(r,d['rings_m'][1:]);edge=max(zip(r,r[1:]+r[:1]),key=lambda pair:math.dist(*pair));theta=math.atan2(edge[1][1]-edge[0][1],edge[1][0]-edge[0][0]);co,si=math.cos(theta),math.sin(theta);uv=transform(lambda x,y:(x*co+y*si,-x*si+y*co),poly);c=polylabel(uv,tolerance=.01);w,h=20.,7.
 while not uv.buffer(-.15).covers(box(c.x-w/2-.5,c.y-h/2-.5,c.x+w/2+.5,c.y+h/2+.5)):w*=.95;h*=.95
 H=d['register_height_m'];d.update({'ring_m':r,'facade_axis_rad_inferred':theta,'roof_frame_uv':[c.x,c.y,w,h],'reference_scope':'Representative-photo-inference from root-approved Shinbanpo Xi101v2; individual photograph number/orientation unknown','height_assumption':f'No source child parts; uniform source footprint envelope{H}m, roof datum unconfirmed; no low wing','body_height_m':H-2.4,'roof_deck_height_m':H-2.15,'model_upper_envelope_m':H,'photo_sha256':'ef17b3643765a6b6db27c47bb0579ec97ef59a194bed67dfcbf3235729b7bac2','inferredFromAssetIds':['bespoke-shinbanpo-xi-101'],'ancestor_glb_sha256':'5560473e7db4ea7d9834fbf4a3ae07df952f638e3064dce85eb0ae2a17f63c38','supersedesAssetIds':binding['supersedes'],'current_owner_asset_ids':[binding['fallbackAssetId']],'binding_status':'root verified published singleton split','modeling_status':'approved representative family; own source geometry and register facts'});(p/'source-data.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(p/'regions.json').write_text(json.dumps([{'id':'uniform-parent-assumption','geometry':mapping(poly),'height_m':H,'body_height_m':H-2.4,'roof_deck_height_m':H-2.15,'floors':d['floors'],'basis':'No source child parts; uniform height assumption','roof_frame_uv':d['roof_frame_uv'],'triangles':[list(q.exterior.coords)[:3] for q in shapely.constrained_delaunay_triangles(poly).geoms]}],indent=2))
 s=(O/'build.py').read_text().replace('SBX101','SBX'+str(t)).replace('Xi101','Xi'+str(t)).replace('shinbanpo-xi-101','shinbanpo-xi-'+str(t));s=s.replace("'register_height_m':82.25","'register_height_m':D['register_height_m']").replace("'model_upper_envelope_m':82.25","'model_upper_envelope_m':D['register_height_m']").replace("'floors':28","'floors':D['floors']").replace('H=82.25;body=79.85;FLOORS=28',"H=D['register_height_m'];body=H-2.40;FLOORS=D['floors']").replace('80.10','(H-2.15)').replace('81.65','(H-.60)').replace('81.95','(H-.30)').replace('80.70','(H-1.55)').replace('for t in [.035,.965]','for t in [.55/L,1-.55/L]').replace("('front',(75,-155),82)","('front',(75,-155),H)").replace("('opposite',(-75,155),82)","('opposite',(-75,155),H)").replace("('side',(170,50),82)","('side',(170,50),H)").replace("('roof',(65,-85),210)","('roof',(65,-85),H*2.55)");s=s.replace("batches={}\n", "s['inferredFromAssetIds']=json.dumps(D['inferredFromAssetIds']);s['ancestor_glb_sha256']=D['ancestor_glb_sha256']\nbatches={}\n");(p/'build.py').write_text(s)
 s=(O/'check-standalone.py').read_text().replace('shinbanpo-xi-101','shinbanpo-xi-'+str(t)).replace("r['floors']==28","r['floors']==D['floors']").replace("r['height_m']==82.25","r['height_m']==D['register_height_m']").replace("-82.25)","-D['register_height_m'])");s=s.replace("assert r['mesh_count']==7", "assert json.loads(s['supersedesAssetIds'])==D['supersedesAssetIds']\nassert r['mesh_count']==7");(p/'check-standalone.py').write_text(s)
 s=(O/'validate.py').read_text().replace("P=R/'data/model-source/bespoke/shinbanpo-xi-101-representative'","P=pathlib.Path(__file__).parent").replace("P.parent/'shinbanpo-xi-research","P.parent.parent/'shinbanpo-xi-research").replace("=='101동'","=='"+str(t)+"동'").replace('shinbanpo-xi-101.glb','shinbanpo-xi-'+str(t)+'.glb').replace("('roof',80.10)","('roof',D['roof_deck_height_m'])").replace('-82.25)',"-D['register_height_m'])").replace('>80.1001',">D['roof_deck_height_m']+.0001").replace("'floors':28","'floors':D['floors']").replace("'height_m':82.25","'height_m':D['register_height_m']").replace("'roof_deck_height_m':80.10","'roof_deck_height_m':D['roof_deck_height_m']");(p/'validate.py').write_text(s)
for i,start in enumerate([102,105],1):
 (P/f'batch-{i}.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in range("+str(start)+","+str(start+3)+"):\n p=P/str(t)/'build.py';exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'check-all.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in range(102,108):\n p=P/str(t)/'check-standalone.py';exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'prior-hashes.json').write_text(json.dumps({str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in O.rglob('*') if p.is_file()},indent=2));(P/'binding-map-frozen.json').write_text(json.dumps(bind,ensure_ascii=False,indent=2));print('six sources and recipes ready')
