import { test, expect } from '@playwright/test';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const assets = JSON.parse(readFileSync('public/models/manifest.json', 'utf8')).assets;
const names = ['반포대교', '올림픽대교', '월드컵대교', '한강대교', '개포중학교', '대치4동주민센터'];
test('bridges, schools, offices, avenues and real transit points render and toggle', async ({ page }) => {
  test.setTimeout(240_000);
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await page.waitForFunction(() => { const a = (window as any).__SEOUL_MAP__; return a?.cityModels && a.getState().terrainReady && a.map.getLayer('transit-labels') && a.map.getLayer('avenue-surface'); });
  await page.locator('#mode-25d').click();
  await page.locator('#exaggeration').evaluate((input: HTMLInputElement) => { input.value = '1'; input.dispatchEvent(new Event('input')); });
  mkdirSync('tests/screenshots', { recursive: true });
  const results = [];
  for (const name of names) {
    const asset = assets.find((a: any) => a.nameKo === name);
    expect(asset).toBeTruthy();
    await page.evaluate((a: any) => (window as any).__SEOUL_MAP__.map.jumpTo({ center: [a.coordinate.lon, a.coordinate.lat], zoom: a.category === 'bridge' ? 14.7 : 17, pitch: 62, bearing: -25 }), asset);
    await page.waitForFunction(id => (window as any).__SEOUL_MAP__.cityModels.getState().models.some((m: any) => m.id === id && m.active && m.drawCount > 0), asset.id, { timeout: 35_000 });
    await page.waitForLoadState('networkidle');
    const state = await page.evaluate(() => (window as any).__SEOUL_MAP__.cityModels.getState());
    expect(state.models.length).toBeGreaterThanOrEqual(assets.length);
    expect(state.models.filter((m: any) => m.loaded).length).toBeLessThanOrEqual(48);
    expect(state.models.filter((m: any) => m.active).length).toBeLessThanOrEqual(32);
    expect(state.models.filter((m: any) => m.error)).toEqual([]);
    await page.screenshot({ path: `tests/screenshots/infrastructure-${asset.id}.png` });
    results.push({ name, id: asset.id, model: state.models.find((m: any) => m.id === asset.id) });
  }
  expect(await page.evaluate(() => (window as any).__SEOUL_MAP__.map.queryRenderedFeatures({ layers: ['avenue-surface'] }).length)).toBeGreaterThan(0);
  await page.locator('#toggle-roads').uncheck();
  expect(await page.evaluate(() => (window as any).__SEOUL_MAP__.map.getLayoutProperty('avenue-surface', 'visibility'))).toBe('none');
  await page.locator('#toggle-public-models').uncheck();
  await expect.poll(() => page.evaluate(() => (window as any).__SEOUL_MAP__.cityModels.getState().models.filter((m: any) => m.id.startsWith('public-') && m.active).length)).toBe(0);
  const publicIds = new Set(assets.filter((a: any) => a.category === 'district-public-office' || a.category === 'k12-school').flatMap((a: any) => a.footprintIds));
  const remaining = await page.evaluate(() => (window as any).__SEOUL_MAP__.cityModels.getState().activeFootprintIds);
  expect(remaining.some((id: string) => publicIds.has(id))).toBe(false);
  const bridge = assets.find((a: any) => a.nameKo === '올림픽대교');
  await page.evaluate((a: any) => (window as any).__SEOUL_MAP__.map.jumpTo({ center: [a.coordinate.lon, a.coordinate.lat], zoom: 16, pitch: 65, bearing: 70 }), bridge);
  await page.waitForFunction(id => (window as any).__SEOUL_MAP__.cityModels.getState().models.some((m: any) => m.id === id && m.active), bridge.id);
  await page.waitForLoadState('networkidle');
  await page.screenshot({ path: 'tests/screenshots/infrastructure-olympic-detail.png' });
  await page.locator('#toggle-bridge-models').uncheck();
  await expect.poll(() => page.evaluate(() => (window as any).__SEOUL_MAP__.cityModels.getState().models.filter((m: any) => m.id.startsWith('bridge-') && m.active).length)).toBe(0);
  const transit = JSON.parse(readFileSync('public/transit.json', 'utf8')).features;
  const rail = transit.find((f: any) => f.properties.kind === 'rail_station');
  const distance = (f: any) => f.geometry.coordinates.reduce((sum: number, n: number, i: number) => sum + (n - rail.geometry.coordinates[i]) ** 2, 0);
  const bus = transit.filter((f: any) => f.properties.kind === 'bus_stop').sort((a: any, b: any) => distance(a) - distance(b))[0];
  expect(Math.sqrt(distance(bus))).toBeLessThan(0.002);
  await page.evaluate((coordinate: [number, number]) => (window as any).__SEOUL_MAP__.map.jumpTo({ center: coordinate, zoom: 17, pitch: 40, bearing: 0 }), bus.geometry.coordinates);
  await page.waitForFunction(() => { const map = (window as any).__SEOUL_MAP__.map; return map.queryRenderedFeatures({ layers: ['transit-bus-points'] }).length > 0 && map.queryRenderedFeatures({ layers: ['transit-rail-points'] }).length > 0; });
  await page.waitForLoadState('networkidle');
  await page.screenshot({ path: 'tests/screenshots/infrastructure-station-and-bus.png' });
  await page.locator('#toggle-bus-stops').uncheck();
  expect(await page.evaluate(() => (window as any).__SEOUL_MAP__.map.getLayoutProperty('transit-bus-points', 'visibility'))).toBe('none');
  await page.locator('#pin-station').uncheck();
  expect(await page.evaluate(() => (window as any).__SEOUL_MAP__.map.getLayoutProperty('transit-rail-points', 'visibility'))).toBe('none');
  expect(errors).toEqual([]);
  writeFileSync('docs/infrastructure-browser-check.json', JSON.stringify({ results, pageErrors: errors, originalBuildingsRestoredOnHide: true, bridgeHideVerifiedWhileVisible: true, railAndBusPointsRendered: true, sampledBusStop: bus, boundedCache: true }, null, 2) + '\n');
});
