import json,hashlib,struct
from pathlib import Path
P=Path(__file__).parent;O=P/'outputs';sha=lambda f:hashlib.sha256(f.read_bytes()).hexdigest()
manifest=json.loads((O/'manifest.json').read_text());inputs=json.loads((P/'selected-input.json').read_text())['sites'];all_sources=[];assets=[];checks=[]
observations={'A15703308': 'Both elevated renders preserve nine 15-floor slab footprints. White-gray walls, broad blank ends and repeated horizontal balcony/window bands agree broadly with the supplied 307/308 street photo. Render windows are regular planar approximations; projecting balcony stacks, individual air conditioners and recessed stair slots are not reproduced. Tower numbers in the photo do not verify all source tower identities.', 'A10026852': 'Both elevated renders show three tall articulated source footprints with dense vertical window stacks and gray-white walls, broadly consistent with the official photograph. Recorded 137/145/137m heights are retained. Photo crowns have taller vertical fins and curved/recessed profiles; the low stepped plant enclosures are a coarse simplification. Podium and terraces are absent; exact tower-to-photo correspondence remains unverified.', 'A15279101': 'Both elevated renders retain all 18 source blocks and show pale walls with orange vertical window panels matching the news photograph at representative scale. Photo includes red lower panel transitions, deeply recessed balconies and a glazed courtyard elevator that are omitted. The source 31/33m heights and 11-13 floor records are retained despite the research summary saying 6-12 floors; the visible photo supports mid-rise massing but cannot verify every tower.'}
for rec in manifest['sites']:
 c=rec['code'];S=next(s for s in inputs if s['code']==c);glb=O/(c+'.glb');data=glb.read_bytes();assert data[:4]==b'glTF';length,kind=struct.unpack_from('<II',data,12);g=json.loads(data[20:20+length]);prims=sum(len(m['primitives']) for m in g['meshes']);assert prims<=7
 ids=json.loads(next(n['extras']['source_footprint_ids'] for n in g['nodes'] if 'source_footprint_ids' in n.get('extras',{})));assert ids==[t['id'] for t in S['towers']]
 sources=[]
 for i,ref in enumerate(rec['design']['references']):
  f=P/ref['imagePath'];v={'id':c+'-source-'+str(i+1),'url':ref['url'],'inputFile':str(f.relative_to(P)),'sha256':sha(f)};sources.append(v);all_sources.append(v)
 hashed=[glb,O/'representative-batch06.blend',P/'selected-input.json',P/'design-recipes.json',P/'build.py',P/'export-compact.py']+[P/s['inputFile'] for s in sources]
 rec.update({'reviewstatus':'coarse-visually-reviewed','comparisons':[{'sourceId':sources[0]['id'],'observation':observations[c]}],'views':[{'file':c+'-overview.png','description':'Southeast elevated overview'},{'file':c+'-reverse.png','description':'Northwest reverse elevated overview'}],'limitations':rec['design']['unknowns'],'reviewedInputs':[{'file':str(f.relative_to(P)),'sha256':sha(f)} for f in hashed],'integrationHold':False,'completionCredit':False})
 (O/(c+'-review.json')).write_text(json.dumps(rec,ensure_ascii=False,indent=2))
 assets.append({'id':'representative-'+c.lower(),'file':str(glb.relative_to(P)),'blendSource':'outputs/representative-batch06.blend','nameKo':S['name'],'coordinate':{'lon':S['anchor']['lon'],'lat':S['anchor']['lat']},'footprintIds':ids,'expectedFootprintIds':S.get('footprintIds',ids),'supersedes':[],'referenceUrl':sources[0]['url'],'uncertainties':rec['limitations'],'representativeForms':2 if c in ['A10024831','A13528004'] else 1,'review':str((O/(c+'-review.json')).relative_to(P)),'integrationHold':False,'completionCredit':False})
 checks.append({'code':c,'bytes':len(data),'drawCalls':prims,'sourcePolygons':len(ids),'twoViewsExist':all((O/(c+'-'+v+'.png')).is_file() for v in ['overview','reverse'])})
(P/'handoff.json').write_text(json.dumps({'siteId':'representative-batch06','constructionMethod':'representative-photo-informed','sources':all_sources,'assets':assets,'mcpEvidence':['mcp-build-evidence.json','mcp-validation-evidence.json'],'recipeFiles':['build.py','export-compact.py','selected-input.json','design-recipes.json'],'geometryValidation':'scene-validation.json'},ensure_ascii=False,indent=2))
(P/'asset-validation.json').write_text(json.dumps(checks,indent=2));print(json.dumps(checks));print('totalBytes',sum(x['bytes'] for x in checks))
