import pathlib,json,hashlib,math,sqlite3,shapely
from shapely.geometry import Polygon,box,mapping
from shapely.ops import transform,polylabel
R=pathlib.Path.cwd();B=R/'data/model-source/bespoke';P=B/'jamsil-ricenz-family';P.mkdir(exist_ok=True);O=B/'jamsil-ricenz-218-representative';src=B/'jamsil-ricenz-research/root-reviewed-source-63.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();assert sha(src)=='75a281842b1ed4b388f168cff914c8183ed942acc9c045986b9583fa0e2bf108';A=json.loads(src.read_text());M=json.loads((B/'jamsil-ricenz-fallback-review/published-model-binding-map.json').read_text());db=sqlite3.connect(R/'data/model-source/residential-survey/register.sqlite');db.row_factory=sqlite3.Row;T=[t for t in range(201,265) if t not in [218,263]];assert len(T)==62
opt=(O/'optimize-v2.py').read_text();opt=opt[opt.index("ob=next(o for o in s.objects"):opt.index('for o in bpy.context.selected_objects')];opt=opt.replace('assert len(removed)>0','assert len(vertical)>0');opt+="\nobjs=[o for o in s.objects if o.type=='MESH'];(P/'optimization-proof.json').write_text(json.dumps({'vertical_rail_bars_unchanged':len(vertical),'white_box_components_unchanged':len(boxes),'removed_fully_enclosed_quad_caps':len(removed),'removed_triangles':len(removed)*2,'white_chunks':len(chunks),'mesh_count':len(objs),'unchanged_coordinates':True,'no_decimation':True,'witnesses':witness},indent=2))\n"
for t in T:
 p=P/str(t);p.mkdir(exist_ok=True);e=next(x for x in A['entries'] if x['tower']==str(t)+'동');b=e['osm_building'];reg=dict(db.execute('select * from reg where id=?',(e['register']['id'],)).fetchone());assert reg==e['register'];g=json.loads(b['geometry']);outer=g['coordinates'][0][:-1];lon=sum(x for x,y in outer)/len(outer);lat=sum(y for x,y in outer)/len(outer);rings=[[[ (x-lon)*111320*math.cos(math.radians(lat)),(y-lat)*111320] for x,y in ring[:-1]] for ring in g['coordinates']];r=rings[0];poly=Polygon(r,rings[1:]);a,z=max(zip(r,r[1:]+r[:1]),key=lambda q:math.dist(*q));theta=math.atan2(z[1]-a[1],z[0]-a[0]);co,si=math.cos(theta),math.sin(theta);uv=transform(lambda x,y:(x*co+y*si,-x*si+y*co),poly);c=polylabel(uv,tolerance=.01);w,h=10.,5.
 while not uv.buffer(-.25).covers(box(c.x-w/2-.2,c.y-h/2-.2,c.x+w/2+.2,c.y+h/2+.2)):w*=.95;h*=.95
 H=float(reg['height']);F=int(reg['floors']);binding=next(x for x in M['bindings'] if x['number']==t);assert binding['sourceFootprintId']==b['id'];d={'tower':str(t),'approved_entry':e,'id':b['id'],'geometry':g,'ring_m':r,'rings_m':rings,'anchor_lonlat':[lon,lat],'register_row':reg,'register_height_m':H,'floors':F,'osm_height_m':b['height_m'],'facade_axis_rad_inferred':theta,'roof_cap_uv':[c.x,c.y,w,h],'body_height_m':H-2.5,'roof_deck_height_m':H-2.25,'model_upper_envelope_m':H,'reference_scope':'Representative-photo-inference from root-approved218v2; KB15524 primary data.photoList[1] shows218, not this sibling. Compass orientation and dimensions unmeasured.','height_assumption':f'No source child parts; uniform own full source footprint envelope{H}m. Low layered roof conservatively inferred from other background towers, not verified own crown; legal roof datum unconfirmed.','source_sha256':sha(src),'photo_sha256':'5fdcf3fe92bbe9d624ee331100e66b386d931629dde77538daf30a1c30546f29','inferredFromAssetIds':['bespoke-jamsil-ricenz-218'],'ancestor_glb_sha256':'955c0a144818db37c0425198e4acad67925edb30e207a6cfcb904188bf83c6f4','supersedesAssetIds':binding['supersedes'],'binding_status':'final root verified published split binding','current_owner_asset_ids':[],'complex_household_discrepancy':'KB5563HH vs65 residential registerrows5562 unresolved; own registerHH retained','scope_exclusions':['263','265'],'photo_list_index':1};(p/'source-data.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(p/'regions.json').write_text(json.dumps([{'id':'uniform-parent-assumption','geometry':mapping(poly),'height_m':H,'body_height_m':H-2.5,'roof_deck_height_m':H-2.25,'floors':F,'basis':d['height_assumption'],'triangles':[list(q.exterior.coords)[:3] for q in shapely.constrained_delaunay_triangles(poly).geoms]}],indent=2))
 s=(O/'build.py').read_text().replace('Ricenz218','Ricenz'+str(t)).replace('jamsil-ricenz-218','jamsil-ricenz-'+str(t)).replace("'register_height_m':88.16","'register_height_m':D['register_height_m']").replace("'model_upper_envelope_m':88.16","'model_upper_envelope_m':D['register_height_m']").replace("'floors':29","'floors':D['floors']").replace('H=88.16;body=85.66;FLOORS=29',"H=D['register_height_m'];body=H-2.5;FLOORS=D['floors']").replace('85.91','(H-2.25)').replace('86.81','(H-1.35)').replace('87.76','(H-.40)').replace('87.935','(H-.225)').replace('88.11','(H-.05)');s=s.replace('for o in bpy.context.selected_objects:o.select_set(False)',opt.replace('Ricenz218','Ricenz'+str(t))+"\nfor o in bpy.context.selected_objects:o.select_set(False)");s=s.replace('batches={}\n',"s['inferredFromAssetIds']=json.dumps(D['inferredFromAssetIds']);s['ancestor_glb_sha256']=D['ancestor_glb_sha256']\nbatches={}\n");(p/'build.py').write_text(s)
 s=(O/'archive-v1/check-standalone.py').read_text().replace('jamsil-ricenz-218','jamsil-ricenz-'+str(t)).replace("r['mesh_count']==6","r['mesh_count']==json.loads((P/'optimization-proof.json').read_text())['mesh_count']").replace("r['floors']==29","r['floors']==D['floors']").replace("r['height_m']==88.16","r['height_m']==D['register_height_m']").replace('-88.16)',"-D['register_height_m'])");s=s.replace("r['initial_scene_restored']=old.name", "assert json.loads(r['supersedesAssetIds'])==D['supersedesAssetIds'];r['initial_scene_restored']=old.name");(p/'check-standalone.py').write_text(s)
 s=(O/'validate.py').read_text().replace("P=R/'data/model-source/bespoke/jamsil-ricenz-218-representative'","P=pathlib.Path(__file__).parent").replace("P.parent/'jamsil-ricenz-research","P.parent.parent/'jamsil-ricenz-research").replace("=='218동'","=='"+str(t)+"동'").replace('jamsil-ricenz-218.glb','jamsil-ricenz-'+str(t)+'.glb').replace("('roof',85.91)","('roof',D['roof_deck_height_m'])").replace('-88.16)',"-D['register_height_m'])").replace('>85.9101',">D['roof_deck_height_m']+.0001").replace("'floors':29","'floors':D['floors']").replace("'height_m':88.16","'height_m':D['register_height_m']").replace("'roof_deck_height_m':85.91","'roof_deck_height_m':D['roof_deck_height_m']");(p/'validate.py').write_text(s)
for i in range(0,len(T),2):
 ts=T[i:i+2];(P/f'batch-{ts[0]}-{ts[-1]}.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in "+repr(ts)+":\n for script in ['build.py','check-standalone.py']:\n  p=P/str(t)/script;exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'prior-hashes.json').write_text(json.dumps({str(p):sha(p) for p in O.rglob('*') if p.is_file()},indent=2));(P/'binding-map-frozen.json').write_text(json.dumps(M,ensure_ascii=False,indent=2));(P/'prepare.py').write_bytes(pathlib.Path(__file__).read_bytes());print('prepared',T)
