import pathlib,json,hashlib,math,sqlite3,shapely
from shapely.geometry import Polygon,box,mapping
from shapely.ops import transform,polylabel
R=pathlib.Path.cwd();B=R/'data/model-source/bespoke';P=B/'seoulforest-riverview-xi-family';P.mkdir(exist_ok=True);O=B/'seoulforest-riverview-xi-104-representative';src=B/'seoulforest-riverview-xi-research/root-reviewed-source-101-107.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();assert sha(src)=='195e5ac0af7503b2091ec414b7ece80e152a4373abbe97db6fdd4c4230a4c67e';A=json.loads(src.read_text());M=json.loads((B/'seoulforest-riverview-xi-fallback-review/published-model-binding-map.json').read_text());db=sqlite3.connect(R/'data/model-source/residential-survey/register.sqlite');db.row_factory=sqlite3.Row;T=[101,102,103,105,106,107]
for t in T:
 p=P/str(t);p.mkdir(exist_ok=True);e=next(x for x in A['entries'] if x['tower']==str(t)+'동');b=e['osm_building'];reg=dict(db.execute('select * from reg where id=?',(e['register']['id'],)).fetchone());assert reg==e['register'];g=json.loads(b['geometry']);outer=g['coordinates'][0][:-1];lon=sum(x for x,y in outer)/len(outer);lat=sum(y for x,y in outer)/len(outer);rings=[[[ (x-lon)*111320*math.cos(math.radians(lat)),(y-lat)*111320] for x,y in ring[:-1]] for ring in g['coordinates']];r=rings[0];poly=Polygon(r,rings[1:]);H=float(reg['height']);F=int(reg['floors']);edges=sorted(enumerate(zip(r,r[1:]+r[:1])),key=lambda v:math.dist(*v[1]),reverse=True);C=None
 for ei,(a,z) in edges:
  dx,dy=z[0]-a[0],z[1]-a[1];L=math.hypot(dx,dy)
  if L<12:continue
  sg=1 if poly.exterior.is_ccw else -1;nx,ny=sg*dy/L,-sg*dx/L
  def pt(st,dep):return (a[0]+dx*st+nx*dep,a[1]+dy*st+ny*dep)
  notch=Polygon([pt(.34,.01),pt(.66,.01),pt(.66,-1.5),pt(.34,-1.5)]);inside=notch.intersection(poly);shell=poly.difference(notch)
  if shell.geom_type!='Polygon' or not shell.is_valid or abs(inside.area-L*.32*1.5)>.001:continue
  bands=[(round(a*F/39),round(z*F/39)) for a,z in [(3,7),(13,17),(23,27),(33,37)]];C={'edge':ei,'left_station':.34,'right_station':.66,'inward_depth_m':1.5,'edge_length_m':L,'outward_normal':[nx,ny],'notch_geometry':mapping(inside),'shell_rings':[list(shell.exterior.coords)[:-1]]+[list(x.coords)[:-1] for x in shell.interiors],'shell_triangles':[list(q.exterior.coords)[:3] for q in shapely.constrained_delaunay_triangles(shell).geoms],'box_bands':bands,'basis':'Representative104photo inference; own longest valid supporting edge >=12m selected, notch wholly inward; compass orientation and widths unmeasured','base_full_footprint_height_m':1.0,'upper_full_footprint_closure_z':H-1.75};theta=math.atan2(dy,dx);break
 assert C is not None,('no sufficiently broad supporting edge',t)
 co,si=math.cos(theta),math.sin(theta);uv=transform(lambda x,y:(x*co+y*si,-x*si+y*co),poly);c=polylabel(uv,tolerance=.01);w,h=10.,5.
 while not uv.buffer(-.25).covers(box(c.x-w/2-.2,c.y-h/2-.2,c.x+w/2+.2,c.y+h/2+.2)):w*=.95;h*=.95
 binding=next(x for x in M['bindings'] if x['number']==t);assert binding['sourceFootprintId']==b['id'];d={'tower':str(t),'approved_entry':e,'id':b['id'],'geometry':g,'ring_m':r,'rings_m':rings,'anchor_lonlat':[lon,lat],'register_row':reg,'register_height_m':H,'floors':F,'osm_height_m':b['height_m'],'facade_axis_rad_inferred':theta,'roof_cap_uv':[c.x,c.y,w,h],'central_recess':C,'body_height_m':H-1.5,'roof_deck_height_m':H-1.25,'model_upper_envelope_m':H,'reference_scope':'Representative-photo-inference from root-approved numbered104v2; photographed building is104, this sibling number and facade orientation unconfirmed','height_assumption':f'No source child parts; uniform own full source footprint maximum{H}m. Inward facade recess/box dimensions, hidden faces and legal roof datum inferred.','source_sha256':sha(src),'photo_sha256':'f5a908ff4383025877fcb419d202977a3f4bc8198592ad0ba13fbe531c965349','inferredFromAssetIds':['bespoke-seoulforest-riverview-xi-104'],'ancestor_glb_sha256':'ecaae1d9619467ff5a6296b434d4a4e2d3d7db25df6347a7feed3308da9e9d77','supersedesAssetIds':binding['supersedes'],'binding_status':'root validated exact split binding','current_owner_asset_ids':[]};(p/'source-data.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(p/'facade-regions.json').write_text(json.dumps(C,indent=2));(p/'regions.json').write_text(json.dumps([{'id':'uniform-parent-assumption','geometry':mapping(poly),'height_m':H,'body_height_m':H-1.5,'roof_deck_height_m':H-1.25,'floors':F,'basis':d['height_assumption'],'triangles':[list(q.exterior.coords)[:3] for q in shapely.constrained_delaunay_triangles(poly).geoms]}],indent=2))
 s=(O/'build.py').read_text().replace('SFRX104','SFRX'+str(t)).replace('Xi104 representative','Xi'+str(t)+' sibling').replace('seoulforest-riverview-xi-104','seoulforest-riverview-xi-'+str(t)).replace("'register_height_m':114.3","'register_height_m':D['register_height_m']").replace("'model_upper_envelope_m':114.3","'model_upper_envelope_m':D['register_height_m']").replace("'floors':39","'floors':D['floors']").replace('H=114.3;body=112.8;FLOORS=39',"H=D['register_height_m'];body=H-1.5;FLOORS=D['floors']").replace('113.05','(H-1.25)').replace('113.55','(H-.75)').replace('114.175','(H-.125)').replace('if ei==9:',"if ei==C['edge']:").replace('[(3,7),(13,17),(23,27),(33,37)]',"C['box_bands']");s=s.replace('batches={}\n',"s['inferredFromAssetIds']=json.dumps(D['inferredFromAssetIds']);s['ancestor_glb_sha256']=D['ancestor_glb_sha256']\nbatches={}\n");(p/'build.py').write_text(s)
 s=(O/'check-standalone.py').read_text().replace('seoulforest-riverview-xi-104','seoulforest-riverview-xi-'+str(t)).replace("r['floors']==39","r['floors']==D['floors']").replace("r['height_m']==114.3","r['height_m']==D['register_height_m']").replace('-114.3)',"-D['register_height_m'])");(p/'check-standalone.py').write_text(s)
 s=(O/'validate.py').read_text().replace("P=R/'data/model-source/bespoke/seoulforest-riverview-xi-104-representative'","P=pathlib.Path(__file__).parent").replace("P.parent/'seoulforest-riverview-xi-research","P.parent.parent/'seoulforest-riverview-xi-research").replace("=='104동'","=='"+str(t)+"동'").replace('seoulforest-riverview-xi-104.glb','seoulforest-riverview-xi-'+str(t)+'.glb').replace("('roof',113.05)","('roof',D['roof_deck_height_m'])").replace('-114.3)',"-D['register_height_m'])").replace('>113.0501',">D['roof_deck_height_m']+.0001").replace("'floors':39","'floors':D['floors']").replace("'height_m':114.3","'height_m':D['register_height_m']").replace("'roof_deck_height_m':113.05","'roof_deck_height_m':D['roof_deck_height_m']");(p/'validate.py').write_text(s)
 s=(O/'validate-recess.py').read_text().replace('seoulforest-riverview-xi-104','seoulforest-riverview-xi-'+str(t)).replace('a=np.array(r[9]);b=np.array(r[10]);',"ei=D['central_recess']['edge'];a=np.array(r[ei]);b=np.array(r[(ei+1)%len(r)]);").replace("[(.415,[(3,7),(23,27)]),(.585,[(13,17),(33,37)])]","[(.415,D['central_recess']['box_bands'][::2]),(.585,D['central_recess']['box_bands'][1::2])]").replace('[0,1,112.55,113.05]',"[0,1,D['body_height_m']-.25,D['roof_deck_height_m']]").replace('7*pitch+.01<z<13*pitch-.01',"D['central_recess']['box_bands'][0][1]*pitch+.01<z<D['central_recess']['box_bands'][1][0]*pitch-.01");(p/'validate-recess.py').write_text(s);print(t,H,F,'edge',C['edge'],'length',round(C['edge_length_m'],3),'bands',bands)
for i,ts in enumerate([T[:2],T[2:4],T[4:]],1):(P/f'batch-{i}.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in "+repr(ts)+":\n p=P/str(t)/'build.py';exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'check-all.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in "+repr(T)+":\n p=P/str(t)/'check-standalone.py';exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n");(P/'prior-hashes.json').write_text(json.dumps({str(p):sha(p) for p in O.rglob('*') if p.is_file()},indent=2));(P/'binding-map-frozen.json').write_text(json.dumps(M,ensure_ascii=False,indent=2));(P/'prepare.py').write_bytes(pathlib.Path(__file__).read_bytes())
