import pathlib,json,hashlib,math,sqlite3,shapely
from shapely.geometry import Polygon,box,mapping
from shapely.ops import transform,polylabel
R=pathlib.Path.cwd();B=R/'data/model-source/bespoke';P=B/'banpo-riche-102-109-family';P.mkdir(exist_ok=True);O=B/'banpo-riche-101-representative';src=B/'banpo-riche-research/root-reviewed-source-101-109.json';assert hashlib.sha256(src.read_bytes()).hexdigest()=='7ec9460889ed3209cf9b543ddc91d8e63179186c8cd97a6214f73c65d4733819';A=json.loads(src.read_text());db=sqlite3.connect(R/'data/model-source/residential-survey/register.sqlite');db.row_factory=sqlite3.Row
for t in range(102,110):
 p=P/str(t);p.mkdir(exist_ok=True);e=next(x for x in A['entries'] if x['tower']==str(t)+'동');b=e['osm_building'];reg=dict(db.execute('select * from reg where id=?',(e['register']['id'],)).fetchone());assert reg==e['register'];g=json.loads(b['geometry']);outer=g['coordinates'][0][:-1];lon=sum(x for x,y in outer)/len(outer);lat=sum(y for x,y in outer)/len(outer);rings=[[[ (x-lon)*111320*math.cos(math.radians(lat)),(y-lat)*111320] for x,y in ring[:-1]] for ring in g['coordinates']];r=rings[0];poly=Polygon(r,rings[1:]);edge=max(zip(r,r[1:]+r[:1]),key=lambda q:math.dist(*q));theta=math.atan2(edge[1][1]-edge[0][1],edge[1][0]-edge[0][0]);co,si=math.cos(theta),math.sin(theta);uv=transform(lambda x,y:(x*co+y*si,-x*si+y*co),poly);c=polylabel(uv,tolerance=.01);w,h=10.,5.
 while not uv.buffer(-.25).covers(box(c.x-w/2-.2,c.y-h/2-.2,c.x+w/2+.2,c.y+h/2+.2)):w*=.95;h*=.95
 area=sum(a[0]*b[1]-b[0]*a[1] for a,b in zip(r,r[1:]+r[:1]));sgn=1 if area>0 else -1;classes=[]
 for i,(a,b) in enumerate(zip(r,r[1:]+r[:1])):
  pre=r[i-1];nxt=r[(i+2)%len(r)];dx,dy=b[0]-a[0],b[1]-a[1];L=math.hypot(dx,dy);ang=math.atan2(dy,dx);cross1=(a[0]-pre[0])*dy-(a[1]-pre[1])*dx;cross2=dx*(nxt[1]-b[1])-dy*(nxt[0]-b[0]);concave=cross1*sgn<-.01 or cross2*sgn<-.01;alignment=abs(math.cos(ang-theta));blank=L<3.3 or (alignment<.45 and L<16) or (concave and L<7.5)
  classes.append({'edge':i,'length_m':L,'angle_rad':ang,'alignment_to_own_longest_edge':alignment,'concave_endpoint':concave,'blank':blank,'basis':'own orientation/length/concavity heuristic; complex-photo-inference, not measured facade'})
 b=e['osm_building'];H=float(reg['height']);F=int(reg['floors']);d={'facade_edge_classes':classes,'tower':str(t),'approved_entry':e,'id':b['id'],'geometry':g,'ring_m':r,'rings_m':rings,'anchor_lonlat':[lon,lat],'register_row':reg,'register_height_m':H,'floors':F,'osm_height_m':b['height_m'],'facade_axis_rad_inferred':theta,'roof_cap_uv':[c.x,c.y,w,h],'body_height_m':H-3.5,'roof_deck_height_m':H-3.25,'model_upper_envelope_m':H,'reference_scope':'Representative-photo-inference from root-approved Banpo Riche101; KB23387 primary complex photo; numbered image and orientation unknown','height_assumption':f'No source child parts; uniform own full source footprint envelope{H}m. Roof cap dimensions and legal roof datum unconfirmed.','source_sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'photo_sha256':'fc46a4b8b46f460ea5798c9339286ef1ed449b45456649d885f5dcfe625df166','inferredFromAssetIds':['bespoke-banpo-riche-101'],'ancestor_glb_sha256':'baba160b199891e02bb41427537cd81dd0e0072418d9eba0b2de3eef9506cd66','supersedesAssetIds':None,'proposedSupersedesAssetIds':['fallback-banpo-riche-'+str(t)],'binding_status':'pending root verified compound splits','current_owner_asset_ids':[]};(p/'source-data.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(p/'regions.json').write_text(json.dumps([{'id':'uniform-parent-assumption','geometry':mapping(poly),'height_m':H,'body_height_m':H-3.5,'roof_deck_height_m':H-3.25,'floors':F,'basis':d['height_assumption'],'triangles':[list(q.exterior.coords)[:3] for q in shapely.constrained_delaunay_triangles(poly).geoms]}],indent=2))
 s=(O/'build.py').read_text().replace('Riche101','Riche'+str(t)).replace('Riche101 representative','Riche'+str(t)+' family').replace('banpo-riche-101','banpo-riche-'+str(t)).replace("'register_height_m':92.5","'register_height_m':D['register_height_m']").replace("'model_upper_envelope_m':92.5","'model_upper_envelope_m':D['register_height_m']").replace("'floors':32","'floors':D['floors']").replace('H=92.5;body=89.0;FLOORS=32',"H=D['register_height_m'];body=H-3.5;FLOORS=D['floors']").replace('89.25','(H-3.25)').replace('89.55','(H-2.95)').replace('91.0','(H-1.5)').replace('92.25','(H-.25)').replace('91.05','(H-1.45)')
 s=s.replace('(H-1.5)5','(H-1.45)')
 s=s.replace('blank=ei in [0,4,6,8,10,14] or L<3.3',"blank=D['facade_edge_classes'][ei]['blank']")
 s=s.replace('batches={}\n',"s['inferredFromAssetIds']=json.dumps(D['inferredFromAssetIds']);s['ancestor_glb_sha256']=D['ancestor_glb_sha256'];s['facade_edge_classes']=json.dumps(D['facade_edge_classes'])\nbatches={}\n");(p/'build.py').write_text(s)
 s=(O/'check-standalone.py').read_text().replace('banpo-riche-101','banpo-riche-'+str(t)).replace("r['floors']==32","r['floors']==D['floors']").replace("r['height_m']==92.5","r['height_m']==D['register_height_m']").replace('-92.5)',"-D['register_height_m'])");(p/'check-standalone.py').write_text(s)
 s=(O/'validate.py').read_text().replace("P=R/'data/model-source/bespoke/banpo-riche-101-representative'","P=pathlib.Path(__file__).parent").replace("P.parent/'banpo-riche-research","P.parent.parent/'banpo-riche-research").replace("=='101동'","=='"+str(t)+"동'").replace('banpo-riche-101.glb','banpo-riche-'+str(t)+'.glb').replace("('roof',89.25)","('roof',D['roof_deck_height_m'])").replace('-92.5)',"-D['register_height_m'])").replace('>89.2501',">D['roof_deck_height_m']+.0001").replace("'floors':32","'floors':D['floors']").replace("'height_m':92.5","'height_m':D['register_height_m']").replace("'roof_deck_height_m':89.25","'roof_deck_height_m':D['roof_deck_height_m']");(p/'validate.py').write_text(s);print(t,H,F)
for i,start in enumerate([102,104,106,108],1):(P/f'batch-{i}.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in range("+str(start)+","+str(start+2)+"):\n p=P/str(t)/'build.py';exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'check-all.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in range(102,110):\n p=P/str(t)/'check-standalone.py';exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'prior-hashes.json').write_text(json.dumps({str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in O.rglob('*') if p.is_file()},indent=2))
