"""Trace LG component layout; optional preparation requires ignored next-review/lg-art-research/retained-source.json. Use frozen committed authored-input for portable recovery."""
import json,math,hashlib,sqlite3,zlib
from pathlib import Path
from shapely.geometry import Polygon,box,LineString
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'data/model-source/bespoke/lg-art-center';OUT.mkdir(parents=True,exist_ok=True)
R=ROOT/'data/model-source/bespoke/next-review/lg-art-research';source=json.loads((R/'retained-source.json').read_text());geo=json.loads(source['geometry']);anchor={'lon':126.82940115000001,'lat':37.56553850254776}
ring=[[(x-anchor['lon'])*111320*math.cos(math.radians(anchor['lat'])),(y-anchor['lat'])*111320] for x,y in geo['coordinates'][0][:-1]]
w,n,e=ring[1],ring[0],ring[5];u=[(n[i]-w[i])/774 for i in range(2)];v=[(e[i]-n[i])/764 for i in range(2)]
def xy(px,py):return [w[i]+(px-140)*u[i]+(py-136)*v[i] for i in range(2)]
def plan(poly):return [xy(x,y) for x,y in poly]
foot=Polygon(ring);high=foot.intersection(Polygon(plan([(402,136),(914,136),(914,900),(402,900)])));low=foot.difference(high)
# Tube direction comes from the north-arrow plan, NOT a literal cardinal-axis guess.
a,b=xy(395,130),xy(303,747);direction=[b[i]-a[i] for i in range(2)];axis=LineString([a,b]);cross=foot.intersection(axis);ends=list(cross.coords)
urls={'architect':'https://www.gansam.com/works/work.php?ptype=view&idx=4030','plan':'https://kiramonthly.com/1422','operator':'https://www.lgart.com/home/display/region/content/JSVFelN3a2tTendqd1FGWHRaQTNQNU15c2N4eW1wSkppNjdDSW9JK0xkTEFhND0=','tube_dimensions':'https://www.lgsciencepark.com/KR/video_detail.php?idx=324&media_type=2&page=1','roof_photo':'https://www.lgart.com/images/contents/img_visit_tab01_01.png','city':'https://sca.seoul.go.kr/seoulhour/site/urbanArch/board/permanent/320'}
sources=[{'url':url,'observations':obs} for url,obs in [(urls['architect'],'Architect states approximate100m square, theatre east/DiscoveryLab west; published physical model, axonometric and sections.'),(urls['plan'],'Architect member project: north-arrow1F floor plan and section; actual plan controls Tube diagonal, distinct theatre/science layout and metro-side notch.'),(urls['operator'],'Operator:10m-high Tube, StepAtrium andGateArc; do not derive entire height from tube.'),(urls['tube_dimensions'],'LGSciencePark:80m Tube and15degree tilted elliptical section. Exactalignment derived fromplan, nominal80m differs from traced source footprint.'),(urls['roof_photo'],'Completed terrace photo: pale oval stage enclosure, lower curved roof rim, terrace openings, separate circular stair turret.'),(urls['city'],'Municipal architectural-award entry:combined ArtsCenter andDiscoveryLab;3above/4below differs from architectmetadata4above/3below; no false exactfloor claim.')]]
for num,obs in [(2,'Completed aerial; full complex,high/low rooflevels, openoval withtransverse beams, lowerpartialarc, terraceandtower.'),(4,'Architect physical models show separation ofmainhall,blackbox,ScienceHall,Tube andStepAtrium.'),(5,'Axonometric explains Tube throughvoid andGateArc intersection.'),(6,'Completed glazed front:highatrium left,lowTube facade right,concretebase anddoor openings.'),(16,'Section shows different roofheights andTube height relative toatrium; unmeasuredproportions.'),(17,'Section identifiesScienceHall,MainHall andBlackBox Theatre.')]:sources.append({'url':f'https://www.gansam.com/admin/data/bbs/works/2307200958386_{num}.png','observations':obs})
D={'siteId':'lg-art-center-seoul','id':'bespoke-lg-art-center-seoul-discovery-lab','nameKo':'LG아트센터 서울·LG디스커버리랩','coordinate':anchor,'oldId':'landmark-2623bbf0-348f-4cec-94c6-dc8ca4977552','footprintId':source['id'],'sourceGeometry':geo,'ring':ring,'planTransform':{'originPixels':[140,136],'originEastNorth':w,'eastNorthPerPixelX':u,'eastNorthPerPixelY':v,'correspondences':'plan(914,136)=sourceN vertex0; plan(140,136)=Wvertex1; plan(914,900)=Evertex5; outline retains sourceSWrecess instead of perfectsquare','northArrow':'upper-right inpublishedKIRAplan'},'highRoof':list(high.exterior.coords)[:-1],'lowRoof':list(low.exterior.coords)[:-1],'estimatedHeights':{'lab':11.7,'main':20.8,'ovalTop':31.2,'upperRecessedRoof':27.2,'lowerArc':23.3},'tube':{'endpoints':[list(x) for x in ends],'nominalLength':80,'tracedLength':cross.length,'majorSemiaxis':6.0,'minorSemiaxis':3.6,'rollDegrees':15,'centerHeight':4.4,'wallThickness':.24,'basis':'15degellipse fromLGSciencePark,10m heightoperator; endpointalignmenttracedKIRAplan; sideaperturesfromcompletedphoto'},'sources':sources,'limits':['Overallheights,ellipsewidth,roofprofiles,facadebaydimensions andglazingmullions areestimated frompublishedplan/sections/photos,notmeasuredsurvey.','The nominal80mTube isroughlymatched to retainedsourceoutline;planregistration andfootprint both approximate.','Stageenclosure is an openoval withrecessedinnerroof andvisibletransversebeams;notanopaque cappedcylinder.','North/eastservicefacade details lessdocumented; conservativeconcrete openings retained asprovisional.','No completeinterior auditorium,belowgroundstation/parking,landscape orartwork reconstruction.','3F/B4 municipal entry conflictswith4F/B3 Gansammetadata;storeylabels not used to claimverifiedtotalheight.','Theone retainedsource footprint covers both ArtsCenter andDiscoveryLab,modeledtogether; nearbySciencePark/botanicalgarden assetsnotclaimed.']}
(OUT/'authored-input.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
print('LG_INPUT',len(ring),'vertices','Tube',round(cross.length,2),'m','areas',round(high.area),round(low.area))
