"""Prepare authored MMCA west-wing inputs; source geometry is never a city template."""
from pathlib import Path
import json,hashlib,datetime
ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/'data/model-source/bespoke/mmca-deoksugung';OUT.mkdir(parents=True,exist_ok=True)
source=OUT/'source-footprint.json'
if not source.exists():source=ROOT/'modeling/bespoke/mmca-deoksugung/source-footprint.json'
s=json.loads(source.read_text())
r={'siteId':'mmca-deoksugung','assetId':'bespoke-mmca-deoksugung','nameKo':'국립현대미술관 덕수궁관 · 석조전 서관','anchor':s['anchor'],'footprintId':s['id'],'oldAssetId':'civic-'+s['id'],'axis':{'U':'along front, near north','V':'outward front, near east','angleRadians':0.022301849,'basis':'Retained OSM long parallel edges. WGS84 anchor is unchanged from current asset.'},'shape':{'southGalleryU':[-33.8,-8.46],'northGalleryU':[7.95,33.16],'galleryV':[-8.15,5.75],'southStairEndU':[-40.33,-33.8],'northStairEndU':[33.16,40.38],'stairEndV':[-6.58,4.35],'centreU':[-8.46,7.95],'centreV':[-9.96,6.72],'porticoU':[-7.47,7.01],'porticoV':[6.72,9.97]},'height':{'floorToFloorOfficialM':[3.4,4.85,4.55],'source':'https://www.mmca.go.kr/upload/artInfo/2015/08/2015080610370456313586.pdf','sourcePdfPage':20,'sourcePrintedPage':21,'galleryParapetTopEstimateM':13.30,'porticoParapetTopEstimateM':14.20,'roofLightTopEstimateM':14.50,'basis':'Official floor-to-floor heights sum12.8m, not a surveyed overall height. Current visible ground datum, cornice/parapet, skylight slopes and portico rise are proportion estimates.'},'facades':{'eastGallery':{'mainWindowsPerWing':10,'mainWindowBottom':4.55,'mainWindowTop':7.80,'mainWindowWidth':1.40,'basementBottom':.88,'basementTop':2.27,'basementWidth':1.22,'upperWall':'broad opaque stone wall; no invented upper office window row','basis':'Official subway6 photo and 2018worksheet p3 elevated photo'},'portico':{'freestandingColumns':6,'columnCentresU':[-6.60,-4.05,-1.50,1.05,3.60,6.15],'columnCentreV':9.12,'columnShaftBottom':3.87,'columnShaftTop':11.73,'shaftRadiusBottom':.47,'shaftRadiusTop':.40,'capitalTop':12.62,'landingHeight':3.40,'stairs':23,'stairsRunEstimate':6.3,'doorWidthEstimate':2.0,'doorHeightEstimate':3.8,'upperWindows':3,'basis':'Official close-up subway7 independently shows six smooth shafts, Corinthian leaf capitals, flat entablature, central doorway, two tall flank windows, three small upper windows; accessibility text states23stairs.'},'westRear':{'status':'unverified rear photograph','treatment':'No duplicated decorative front portico; plain source-aligned stone volume, lower service openings only provisionally inferred from 1F visitor plan; no claim of exact opening count.'},'northSouthEnds':{'status':'plan-supported separate stair end masses; elevation partially unverified','treatment':'Narrower recessed stair ends, conservative lower doors and upper small windows; no invented colonnade or connection to east wing.'}},'roof':{'sourceInnerRings':s['geometry']['coordinates'][1:],'interpretation':'Not treated as ground-level courtyards: official visitor plans show occupied galleries and central lounge. Four low wing roof-light covers on source inner-ring locations are provisional. Elevated2018photo confirms an opaque pale pitched central roof with a small dark northern gable opening, authored separately. No measured pitch or glass specification.'},'sources':[
 {'url':'https://www.mmca.go.kr/deoksugung/accessibility/subway.do','observations':'Museum operator states23stairs to2F entrance; current facade photographs directly inspected.'},
 {'url':'https://www.mmca.go.kr/asset/images/accessibility/deoksugung/gettingHere/subway_6.jpg','observations':'Long flat stone wings, one tall window row, squat basement windows, blank upper gallery wall, central elevated columned entry; fountain is separate and excluded.'},
 {'url':'https://www.mmca.go.kr/asset/images/accessibility/deoksugung/gettingHere/subway_7.jpg','observations':'Six round smooth columns with Corinthian foliage/volute capitals; deep portico and rectangular flat entablature, broad23stepapproach, three upper windows, central doorway and tall flank windows. Photograph includes2025exhibitionbanner, exactcapturedateunspecified.'},
 {'url':'https://www.mmca.go.kr/eng/visitingInfo/deoksugungInfo.do','observations':'Official1F/2F/3F visitor diagrams show central hall, two long galleries and narrower terminal stair/service zones; schematic not measuredCAD.'},
 {'url':'https://www.mmca.go.kr/assetGwanEng/images/contents/deoksugung/2f_img_pc.png','observations':'Central entrance projection and lateral galleries; matched to source N/S plan topology.'},
 {'url':'https://www.mmca.go.kr/upload/artInfo/2015/08/2015080610370456313586.pdf','observations':'2014annualreport PDF20/printed21 visually inspected: Deoksugung westwing,1938-03-31completion; floorheights3.40/4.85/4.55m, concrete/stone construction. These are not overall height.'},
 {'url':'https://www.mmca.go.kr/upload/board/201309040000011/2018/05/2018052910540905316321.pdf','observations':'2018May MMCA education workbook PDF3 directly inspected: PalaceManagement credited elevated exterior photo shows raised central roof, lower wing parapet and ordered window/cornice. Decorative collage combines east+west motifs and is not used as a west-wing elevation.'}],
 'uncertainties':['Exact ground and roof datums, total height, capital carving and moulding dimensions remain proportional estimates.','Rear and terminal service elevations lack individually identified completion photos and are conservative approximations.','Source polygon has five internal rings; skylight interpretation and roof pitch are provisional rather than excavated open courtyards.','Current temporary exhibition banners, sculptures, fountains, east wing and separately identified connecting passage are excluded.']}
(OUT/'authored-input.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print('Prepared',r['assetId'])
