#!/usr/bin/env python3
"""Preserve two archived compounds while separating five Acro Riverview towers."""
import argparse
import json
from collections import Counter

from split_caelitus_fallback import ROOT, decode, sha
from split_banpo_fallbacks import partition
from split_prestige_fallbacks import canonical_sha, replay, triangle_signatures
from publish_bespoke_models import replace_batch

STAGE = ROOT / 'data/model-source/bespoke/acro-riverview-fallback-review'
CONFIGS = [
    ('apt-a10026227', 'd42448c000366195e432e731b7b50edc71e17a40cb769e8b01009aa3ea218d8f',
     [101, 102, 103], ['77c66b26-e411-42e1-bac0-339e92925576', '28668f28-4296-4b97-898b-b61b7cadf0eb'], 'docs/APARTMENT_400_PROVENANCE.json'),
    ('apt-a13790723', '3b9248d428e4445801616d4527281d1392df1bd080a39b467a7b1a63edfb7bad',
     [104, 105], [], 'docs/APARTMENT_100_PROVENANCE.json'),
]


def encoded(value):
    return (json.dumps(value, ensure_ascii=False, indent=2) + '\n').encode()


def prepare():
    folder = ROOT / 'public/models'
    base = json.loads((folder / 'manifest.json').read_text())
    matches = json.loads((folder / 'footprint-matches.json').read_text())
    current = json.loads((folder / 'generic-corrections.json').read_text())
    identity = json.loads((ROOT / 'docs/model-audit/acro-riverview-source-identity.json').read_text())
    assert identity['sourceSha256'] == '1d0a4f420d72a16bf5c82e4e8aeede8ab56930be7882809eb324fdb3a776f7aa'
    towers = {row['number']: row['sourceId'] for row in identity['towers']}
    assert sorted(towers) == list(range(101, 106)) and len(set(towers.values())) == 5
    added, documents, proofs, bindings = [], {}, [], []
    for source_id, source_sha, numbers, neighbors, provenance in CONFIGS:
        source = next(a for a in base['assets'] if a['id'] == source_id)
        original = (folder / source['model']).read_bytes()
        assert sha(original) == source['sha256'] == source_sha
        assert set(matches[source_id]) == {towers[n] for n in numbers} | set(neighbors)
        owners, authoring = replay(source, original, matches[source_id], provenance)
        cfg = {'site': 'acro-riverview-' + str(numbers[0]), 'source': source_id, 'sha': source_sha,
            'count': len(matches[source_id]), 'removeApartmentCode': True,
            'remainingName': '아크로리버뷰 인접 기존112·113동 (기존 추정 모형)',
            'parts': [(f'fallback-acro-riverview-{n}', f'아크로리버뷰 신반포 {n}동', towers[n]) for n in numbers],
            'limits': ['Only original indexed triangles, attributes, materials and shared terrain anchor are partitioned; no photo-completion credit.',
                'Two unrelated source buildings112/113 remain separately in the original main compound residual. Their missing source heights and legacy inferred heights remain unchanged.',
                'The archive labeled Shinbanpo5 actually contains the verified Riverview104/105 polygons; replacement labels correct this identity without changing archived geometry.',
                'Original concave-footprint convex-hull approximations are retained and explicitly counted.']}
        correction, files, proof = partition(cfg, folder, base, matches)
        gltf, primitives = decode(original)
        signatures = {fid: Counter() for fid in matches[source_id]}
        for primitive, attributes, indices in primitives:
            tagged = owners[primitive['material']]
            assert len(tagged) == len(indices)
            material = json.dumps(gltf['materials'][primitive['material']], sort_keys=True, separators=(',', ':')).encode()
            for fid, index in zip(tagged, indices):
                signatures[fid][sha(material + b''.join(k.encode() + attributes[k][index].tobytes() for k in sorted(attributes)))] += 1
        for asset in correction['assets']:
            expected = sum((signatures[fid] for fid in asset['footprintIds']), Counter())
            assert triangle_signatures(files[folder / asset['model']]) == expected, 'Per-source triangle emission ownership differs'
            assert asset['coordinate'] == source['coordinate'] and 'apartmentCode' not in asset and 'householdCount' not in asset
        assert sum(a['triangles'] for a in correction['assets']) == source['triangles']
        proof['sourceAuthoringReplay'] = authoring
        proof['ownershipMethod'] += ' Independently regenerated byte-exact archived GLB and checked per-source triangle-signature multiplicity against every output.'
        files[ROOT / f"docs/model-audit/{cfg['site']}-generic-split.json"] = encoded(proof)
        documents.update(files)
        for n in numbers:
            asset = next(a for a in correction['assets'] if a['id'] == f'fallback-acro-riverview-{n}')
            assert asset['footprintIds'] == [towers[n]]
            bindings.append({'number': n, 'sourceFootprintId': towers[n], 'fallbackAssetId': asset['id'],
                'supersedes': [asset['id']], 'fallbackModel': asset['model'], 'fallbackSha256': asset['sha256']})
        added.append(correction)
        proofs.append(proof)
    source_ids = {c['sourceId'] for c in added}
    prior = [c for c in current['corrections'] if c['sourceId'] not in source_ids]
    binding = {'version': 1, 'complex': '아크로리버뷰 신반포', 'sourceIdentity': 'docs/model-audit/acro-riverview-source-identity.json',
        'bindings': bindings, 'preservedNeighborSourceIds': CONFIGS[0][3]}
    audit = {'version': 1, 'sources': proofs, 'preservedPriorCorrectionIds': [c['sourceId'] for c in prior],
        'preservedPriorCorrectionsCanonicalSha256': canonical_sha(prior), 'sourceTriangles': sum(p['sourceTriangles'] for p in proofs),
        'hullApproximationTriangles': sum(p['trianglesAssignedWithinUniqueSourceConvexHull'] for p in proofs)}
    documents[ROOT / 'docs/model-audit/acro-riverview-generic-split.json'] = encoded(audit)
    documents[ROOT / 'docs/model-audit/acro-riverview-fallback-bindings.json'] = encoded(binding)
    current['corrections'] = [*prior, *added]
    documents[folder / 'generic-corrections.json'] = encoded(current)
    return documents, audit, binding


def main(stage_only):
    documents, audit, binding = prepare()
    STAGE.mkdir(parents=True, exist_ok=True)
    for path, data in documents.items():
        dest = STAGE / path.relative_to(ROOT)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
    (STAGE / 'published-model-binding-map.json').write_bytes(encoded(binding))
    if not stage_only:
        path = ROOT / 'public/data/deployment-assets.json'
        deployment = json.loads(path.read_text())
        for file, data in documents.items():
            if file.is_relative_to(ROOT / 'public/models'):
                deployment['files'][str(file.relative_to(ROOT))] = sha(data)
        documents[path] = encoded(deployment)
        replace_batch([], documents)
    print(json.dumps({'stageOnly': stage_only, 'sourceTriangles': audit['sourceTriangles'], 'outputs': len(binding['bindings']),
        'hullApproximationTriangles': audit['hullApproximationTriangles'], 'priorCorrections': len(audit['preservedPriorCorrectionIds'])}))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--stage-only', action='store_true')
    main(parser.parse_args().stage_only)
