import pathlib,json,hashlib,math,sqlite3,shapely
from shapely.geometry import Polygon,box,mapping
from shapely.ops import transform,polylabel
R=pathlib.Path.cwd();B=R/'data/model-source/bespoke';P=B/'jamsil-els-family';P.mkdir(exist_ok=True);O=B/'jamsil-els-120-representative';src=B/'jamsil-els-research/root-reviewed-source-101-172.json';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();assert sha(src)=='e8f2a54420654efcd85cb945797623d85384efa60529f88393acee96645f26e0';A=json.loads(src.read_text());M=json.loads((B/'jamsil-els-fallback-review/published-model-binding-map.json').read_text());db=sqlite3.connect(R/'data/model-source/residential-survey/register.sqlite');db.row_factory=sqlite3.Row;T=[t for t in range(101,173) if t!=120];assert len(T)==71
for t in T:
 p=P/str(t);p.mkdir(exist_ok=True);e=next(x for x in A['entries'] if x['tower']==str(t)+'동');b=e['osm_building'];reg=dict(db.execute('select * from reg where id=?',(e['register']['id'],)).fetchone());assert reg==e['register'];g=json.loads(b['geometry']);outer=g['coordinates'][0][:-1];lon=sum(x for x,y in outer)/len(outer);lat=sum(y for x,y in outer)/len(outer);rings=[[[ (x-lon)*111320*math.cos(math.radians(lat)),(y-lat)*111320] for x,y in ring[:-1]] for ring in g['coordinates']];r=rings[0];poly=Polygon(r,rings[1:]);a,z=max(zip(r,r[1:]+r[:1]),key=lambda q:math.dist(*q));theta=math.atan2(z[1]-a[1],z[0]-a[0]);co,si=math.cos(theta),math.sin(theta);uv=transform(lambda x,y:(x*co+y*si,-x*si+y*co),poly);c=polylabel(uv,tolerance=.01);w,h=14.,5.
 while not uv.buffer(-.4).covers(box(c.x-w/2-.2,c.y-h/2-.2,c.x+w/2+.2,c.y+h/2+.2)):w*=.95;h*=.95
 assert w>2 and h>.5
 H=float(reg['height']);F=int(reg['floors']);binding=next(x for x in M['bindings'] if x['number']==t);assert binding['sourceFootprintId']==b['id'];d={'tower':str(t),'approved_entry':e,'id':b['id'],'geometry':g,'ring_m':r,'rings_m':rings,'anchor_lonlat':[lon,lat],'register_row':reg,'register_height_m':H,'floors':F,'osm_height_m':b['height_m'],'facade_axis_rad_inferred':theta,'roof_cap_uv':[c.x,c.y,w,h],'body_height_m':H-2.5,'roof_deck_height_m':H-2.25,'model_upper_envelope_m':H,'reference_scope':'Representative-photo-inference from root-approved Els120. KB15617 primary data.photoList[0] shows120 background blankwall; foreground balcony/brown base is unnumbered complex detail. Own sibling number/orientation/hiddenfaces/spacing not photo-verified.','height_assumption':f'No source child parts; uniform own full source footprint envelope{H}m. Roof grille/raised pale ends inferred from approved representative, not measured own crown; legal roof datum unconfirmed.','source_sha256':sha(src),'photo_sha256':'93ef9a4d3b8d702e1343c70a27f347667fbec50c5855a269172728b4545aa8c4','inferredFromAssetIds':['bespoke-jamsil-els-120'],'ancestor_glb_sha256':'edd0849382b49cee00bfc6c4238c98dfe4a1dc51636b20cba17f28d9e0e18fcc','supersedesAssetIds':binding['supersedes'],'binding_status':'root verified staged split binding; public application pending','current_owner_asset_ids':[],'complex_household_discrepancy':'KB5678HH; own registerHH retained','scope_exclusions':[],'photo_list_index':0};(p/'source-data.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(p/'regions.json').write_text(json.dumps([{'id':'uniform-parent-assumption','geometry':mapping(poly),'height_m':H,'body_height_m':H-2.5,'roof_deck_height_m':H-2.25,'floors':F,'basis':d['height_assumption'],'triangles':[list(q.exterior.coords)[:3] for q in shapely.constrained_delaunay_triangles(poly).geoms]}],indent=2))
 for name in ['build.py','check-standalone.py','validate.py']:
  s=(O/name).read_text().replace('Els120','Els'+str(t)).replace('jamsil-els-120','jamsil-els-'+str(t)).replace("=='120동'","=='"+str(t)+"동'").replace("P.parent/'jamsil-els-research","P.parent.parent/'jamsil-els-research");s=s.replace('numbered-photo gray blankwall','representative-inferred gray blankwall').replace('photo120 wall and unnumbered complex balcony inference','approved representative wall and balcony inference');(p/name).write_text(s)
for i in range(0,len(T),2):
 ts=T[i:i+2];(P/f'batch-{ts[0]}-{ts[-1]}.py').write_text("import pathlib\nP=pathlib.Path(__file__).parent\nfor t in "+repr(ts)+":\n for script in ['build.py','check-standalone.py']:\n  p=P/str(t)/script;exec(compile(p.read_text(),str(p),'exec'),{'__file__':str(p)})\n")
(P/'prior-hashes.json').write_text(json.dumps({str(p):sha(p) for p in O.rglob('*') if p.is_file()},indent=2));(P/'binding-map-frozen.json').write_text(json.dumps(M,ensure_ascii=False,indent=2));(P/'prepare.py').write_bytes(pathlib.Path(__file__).read_bytes());(P/'visually-reviewed-towers.json').write_text('[]')
for name in ['verify-contact.py','finish-reviewed.py']:
 s=(B/'jamsil-ricenz-family'/name).read_text().replace('jamsil-ricenz','jamsil-els').replace("'target':62","'target':71");(P/name).write_text(s)
print('prepared',len(T));print('121/122',[next(x for x in M['bindings'] if x['number']==t)['supersedes'] for t in [121,122]])
