import pathlib,json,hashlib
P=pathlib.Path(__file__).parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
prior=json.loads((P/'prior-hashes.json').read_text());changed=[k for k,v in prior.items() if sha(pathlib.Path(k))!=v];assert not changed;(P/'prior-stage-preservation.json').write_text(json.dumps({'checked_files':len(prior),'changed':changed},indent=2))
items=[]
for t in map(str,range(115,130)):
 p=P/t;d=json.loads((p/'source-data.json').read_text());g=json.loads((p/'geometry-proof.json').read_text());s=json.loads((p/'standalone-validation.json').read_text());assert all((p/(v+'.png')).exists() for v in ['front','opposite','side','roof']);assert s['source_id']==d['id'] and json.loads(s['supersedesAssetIds'])==d['supersedesAssetIds']
 h={f.name:sha(f) for f in p.iterdir() if f.is_file() and f.name!='final-hashes.json'};(p/'final-hashes.json').write_text(json.dumps(h,indent=2))
 items.append({'assetId':'bespoke-banpo-xi-'+t,'tower':t,'footprintId':d['id'],'anchor_lonlat':d['anchor_lonlat'],'registerId':d['register_row']['id'],'registerRowNumber':d['register_row']['row_number'],'registerHeightM':d['register_height_m'],'modeledUpperEnvelopeM':d['register_height_m'],'osmHeightM':d['height_m'],'floors':d['floors'],'households':int(d['register_row']['households']),'lowerWingFloorsInferred':d['lower_wing_floors_inferred'],'roofDatum':d['height_basis'],'scope':d['reference_scope'],'inferredFromAssetIds':['bespoke-banpo-xi-101'],'supersedesAssetIds':d['supersedesAssetIds'],'binding_status':d['binding_status'],'glbPath':t+'/banpo-xi-'+t+'.glb','blendPath':t+'/banpo-xi-'+t+'-authored.blend','sourceDataPath':t+'/source-data.json','regionsPath':t+'/regions.json','views':{v:t+'/'+v+'.png' for v in ['front','opposite','side','roof']},'sourceSha256':h['source-data.json'],'glbSha256':h['banpo-xi-'+t+'.glb'],'blendSha256':h['banpo-xi-'+t+'-authored.blend'],'maximumSurfaceProjectionM':g['maximum_surface_vertex_projection_m'],'status':'staged, unpublished, independent root review pending'})
(P/'bundle.json').write_text(json.dumps(items,ensure_ascii=False,indent=2));(P/'bundle-hashes.json').write_text(json.dumps({str(f.relative_to(P)):sha(f) for f in P.rglob('*') if f.is_file() and f.name!='bundle-hashes.json'},indent=2));print('frozen',len(items),'models; previous',len(prior),'files unchanged; bundle',sha(P/'bundle.json'))
