import pathlib,json,hashlib,math,sqlite3
from shapely.geometry import Polygon,box,mapping,LineString
from shapely.ops import transform, split, unary_union
import shapely
R=pathlib.Path.cwd();B=R/'data/model-source/bespoke';P=B/'banpo-xi-115-129-family';P.mkdir(exist_ok=True);src=B/'banpo-xi-all44-research/modeling-ready-101-144.json';assert hashlib.sha256(src.read_bytes()).hexdigest()=='45660daf8938c9731fcd51b74310084afd0ebf3e7744b2652a62a45bd1b3d3d1';A=json.loads(src.read_text());db=sqlite3.connect(R/'data/model-source/residential-survey/register.sqlite');db.row_factory=sqlite3.Row
old=B/'banpo-xi-101-102-104-register-corrected';(P/'prior-hashes.json').write_text(json.dumps({str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in old.rglob('*') if p.is_file()},indent=2))
for t in map(str,range(115,130)):
 e=next(e for e in A['entries'] if e['tower']==t+'동');b=e['osm_building'];reg=dict(db.execute('select * from reg where id=?',(e['register']['id'],)).fetchone());assert reg==e['register'];g=json.loads(b['geometry']);r=g['coordinates'][0][:-1];lon=sum(x for x,y in r)/len(r);lat=sum(y for x,y in r)/len(r);ring=[[(x-lon)*111320*math.cos(math.radians(lat)),(y-lat)*111320] for x,y in r];poly=Polygon(ring);assert poly.is_valid
 a,z=max(zip(ring,ring[1:]+ring[:1]),key=lambda q:math.dist(*q));theta=math.atan2(z[1]-a[1],z[0]-a[0]);co,si=math.cos(theta),math.sin(theta);uv=transform(lambda x,y:(x*co+y*si,-x*si+y*co),poly);mnx,mny,mxx,mxy=uv.bounds;cut=mny+(mxy-mny)*.42;upuv=uv.intersection(box(mnx-1,cut,mxx+1,mxy+1));line=LineString([(u*co-cut*si,u*si+cut*co) for u in [-1000,1000]]);pieces=list(split(poly,line).geoms);upper=unary_union([q for q in pieces if -q.representative_point().x*si+q.representative_point().y*co>=cut]);lower=unary_union([q for q in pieces if -q.representative_point().x*si+q.representative_point().y*co<cut]);F=int(reg['floors']);H=float(reg['height']);lf=F-max(4,round(F*.17));body=H-3;lo=body*lf/F
 def region(name,p,f,h):
  parts=list(p.geoms) if hasattr(p,'geoms') else [p];return {'id':name,'geometry':mapping(p),'floors_inferred':f,'body_height_m':h,'height_m':h+3,'inference':'Complex photo derived step; region and wing floors unverified for numbered tower','polygons':[{'ring':list(q.exterior.coords)[:-1],'triangles':[list(tr.exterior.coords)[:3] for tr in shapely.constrained_delaunay_triangles(q).geoms]} for q in parts]}
 regions=[region('lower-photo-inferred',lower,lf,lo),region('upper-photo-inferred',upper,F,body)]
 for q in regions:
  pp=shapely.from_geojson(json.dumps(q['geometry']));pu=transform(lambda x,y:(x*co+y*si,-x*si+y*co),pp);parts=list(pu.geoms) if hasattr(pu,'geoms') else [pu];from shapely.ops import polylabel
  largest=max(parts,key=lambda p:p.area);c=polylabel(largest,tolerance=.01);radius=c.distance(largest.boundary);w=min(8,radius);d=min(4,radius);q['roof_frame_uv']=[c.x,c.y,w,d]
  assert pu.covers(box(c.x-w/2-.25,c.y-d/2-.25,c.x+w/2+.25,c.y+d/2+.25))
 d={**b,'geometry':g,'ring_m':ring,'anchor_lonlat':[lon,lat],'facade_axis_rad_inferred':theta,'register_row':reg,'register_height_m':H,'floors':F,'lower_wing_floors_inferred':lf,'body_height_m':body,'lower_body_height_m':lo,'supersedesAssetIds':None,'binding_status':'pending root binding map','reference_scope':'Complex-photo-inference from KB page15891; individual numbered photograph and orientation unverified; lower-wing region and floors inferred, not surveyed','height_basis':'Register height used as ornament-inclusive upper envelope; legal roof measurement datum unconfirmed','ancestor':'bespoke-banpo-xi-101','source_map_sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'source_membership':e['membership_evidence'],'child_parts':e['child_parts']};p=P/t;p.mkdir(exist_ok=True);(p/'source-data.json').write_text(json.dumps(d,ensure_ascii=False,indent=2));(p/'regions.json').write_text(json.dumps(regions,indent=2))
print('prepared15')
