import pathlib,json,math,hashlib,sqlite3,shapely,sys,copy
from shapely.geometry import Polygon,mapping
R=pathlib.Path.cwd();B=R/'data/model-source/bespoke';ROOT=B/'songpa-helio-city-family';O=B/'songpa-helio-city-416-representative';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();src=B/'songpa-hellio-city-research/root-reviewed-source-84.json';assert sha(src)=='227fbfd6ceb76dd3850c9746b4211f7ed9cd3fbeec2400c95537acde8e7e90bb';A=json.loads(src.read_text());M=json.loads((B/'songpa-helio-city-fallback-review/published-model-binding-map.json').read_text());db=sqlite3.connect(R/'data/model-source/residential-survey/register.sqlite');db.row_factory=sqlite3.Row
assert sha(O/'songpa-helio-city-416.glb')=='858d87c1271e57a17ccc6ab3b9b11fb8045bd3dca084e316565c800c495409d9'
if not (ROOT/'representative-preservation.json').exists():(ROOT/'representative-preservation.json').write_text(json.dumps({str(p):sha(p) for p in [O/'songpa-helio-city-416.glb',O/'songpa-helio-city-416-authored.blend',src]},indent=2))
def data(q):return {'rings':[list(q.exterior.coords)[:-1]]+[list(v.coords)[:-1] for v in q.interiors],'triangles':[list(t.exterior.coords)[:3] for t in shapely.constrained_delaunay_triangles(q).geoms]}
for num in map(int,sys.argv[1:]):
 assert num!=416;N=str(num);P=ROOT/N;P.mkdir(exist_ok=False);e=next(x for x in A['entries'] if x['tower']==N+'동');sourcebuilding=e['osm_building'];reg=dict(db.execute('select * from reg where id=?',(e['register']['id'],)).fetchone());assert reg==e['register'] and not e['child_parts'];g=json.loads(sourcebuilding['geometry']);outer=g['coordinates'][0][:-1];lon=sum(x for x,y in outer)/len(outer);lat=sum(y for x,y in outer)/len(outer);rings=[[[ (x-lon)*111320*math.cos(math.radians(lat)),(y-lat)*111320] for x,y in ring[:-1]] for ring in g['coordinates']];r=rings[0];poly=Polygon(r,rings[1:]);lens=[math.dist(a,b) for a,b in zip(r,r[1:]+r[:1])];area=sum(a[0]*b[1]-b[0]*a[1] for a,b in zip(r,r[1:]+r[:1]));threshold={307:18,312:15,313:17,314:17,315:16.2}.get(num,16 if len(r)<=5 else 12);choices=[i for i,L in enumerate(lens) if 7<L<threshold];ei=max(choices,key=lambda i:lens[i]) if choices else min(range(len(r)),key=lambda i:abs(lens[i]-11));a,b=r[ei],r[(ei+1)%len(r)];L=lens[ei];tx,ty=(b[0]-a[0])/L,(b[1]-a[1])/L;nx,ny=(ty,-tx) if area>0 else(-ty,tx);cx,cy=(a[0]+b[0])/2,(a[1]+b[1])/2
 def cutpoly(a,b,t,w,depth):
  L=math.dist(a,b);tx,ty=(b[0]-a[0])/L,(b[1]-a[1])/L;nx,ny=(ty,-tx) if area>0 else(-ty,tx);cx=a[0]+(b[0]-a[0])*t;cy=a[1]+(b[1]-a[1])*t;return Polygon([(cx+tx*u+nx*v,cy+ty*u+ny*v) for u,v in [(-w/2,.5),(w/2,.5),(w/2,-depth),(-w/2,-depth)]])
 H=float(reg['height']);F=int(reg['floors']);body=H-1.2;pitch=body/F;entrywidth=min(L*.55,L-1);entrycut=cutpoly(a,b,.5,entrywidth,.85);assert poly.difference(entrycut).geom_type=='Polygon';axis=max(range(len(r)),key=lambda i:lens[i]);aa,bb=r[axis],r[(axis+1)%len(r)];binding=next(x for x in M['bindings'] if x['number']==num);assert binding['sourceFootprintId']==sourcebuilding['id'];d=copy.deepcopy(json.loads((O/'source-data.json').read_text()));d.update(tower=N,approved_entry=e,id=sourcebuilding['id'],geometry=g,ring_m=r,rings_m=rings,anchor_lonlat=[lon,lat],register_row=reg,register_height_m=H,floors=F,osm_height_m=sourcebuilding['height_m'],facade_axis_rad_inferred=math.atan2(bb[1]-aa[1],bb[0]-aa[0]),body_height_m=body,roof_deck_height_m=H-1.05,model_upper_envelope_m=H,entry={'edge':ei,'center_m':[cx,cy],'outward_normal':[nx,ny],'unit_tangent':[tx,ty],'width_m':entrywidth,'depth_m':.85,'bottom_m':.18,'top_m':pitch*1.6,'basis':'Own selected shortwall,55 percent width inferred from representative416; individual entry orientation not photographed'},label={'text':N,'edge':ei,'basis':'Source/register building number; placement inferred from416, not individually photo-verified'},roof_rail_ring=list(poly.buffer(-.22).exterior.coords)[:-1],reference_scope='Representative-photo-inference from root-approved numbered416 KB32148 photoList[2], ancestor v3. Own building not individually identified in photograph. Frame stations, service/blank edge roles, entry and number positions, orientation and widths inferred for own shape; no surveyed facade dimensions.',height_assumption=f'No child parts: uniform own footprint envelope{H}m{F}F assumed. Own full grade/roof preserved; facade cavities only. Roof railing inside registered envelope; legal roof datum unmeasured.',inferredFromAssetIds=['bespoke-songpa-helio-city-416'],ancestor_glb_sha256=sha(O/'songpa-helio-city-416.glb'),supersedesAssetIds=binding['supersedes'],current_owner_asset_ids=binding['supersedes'],binding_status='root published fallback mapping exact own source join',complex_household_discrepancy=f'Official/KAPT parcel479 versus register913 unresolved; root exact road345/84rows/9510HH match. Own{N} households{reg.get("households")} retained.',blank_edge_threshold_m_inferred=threshold)
 groups={};cuts=[]
 for edge,(a,b) in enumerate(zip(r,r[1:]+r[:1])):
  L=lens[edge]
  if L<threshold:continue
  count=max(4,round(L/3.7));bw=L/count;starts=[max(2,round(F*.17)),min(F-3,round(F*.67)),min(F-3,round(F*.34))];gs=[[1,starts[0],starts[0]+2],[count-2,starts[1],starts[1]+2],[count//2+1,starts[2],starts[2]+2]];groups[str(edge)]=gs
  for ji,fs,fe in gs:cuts.append({'z0':fs*pitch+.17,'z1':fe*pitch-.17,'cut':cutpoly(a,b,(ji+.5)/count,bw*.96-.34,.38)})
 d['frame_groups']=groups;bands=[];levels=sorted(set([0,.18,d['entry']['top_m'],2*pitch,body]+[z for q in cuts for z in [q['z0'],q['z1']]]))
 for z0,z1 in zip(levels,levels[1:]):
  mid=(z0+z1)/2;q=poly
  if .18<mid<d['entry']['top_m']:q=q.difference(entrycut)
  for c in cuts:
   if c['z0']<mid<c['z1']:q=q.difference(c['cut'])
  assert q.is_valid and q.geom_type=='Polygon',(num,z0);bands.append({'z0':z0,'z1':z1,'material':'base' if mid<2*pitch else 'white','shape':data(q)})
 for name,obj in [('source-data.json',d),('binding-map-frozen.json',binding),('body-bands.json',bands),('entry-shape.json',{'full':data(poly),'notched':data(poly.difference(entrycut)),'cut_geometry':mapping(entrycut)}),('regions.json',[{'id':'uniform-parent-assumption','geometry':mapping(poly),'height_m':H,'body_height_m':body,'roof_deck_height_m':H-1.05,'floors':F,'basis':d['height_assumption'],**data(poly)}])]: (P/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2))
 s=(O/'build.py').read_text().replace('Helio416','Helio'+N).replace('songpa-helio-city-416','songpa-helio-city-'+N).replace("cu.body='416'",f"cu.body='{N}'").replace('Photo verified416','Source numbered'+N).replace('416 verified number','Source '+N+' inferred number').replace('blank=L<16',"blank=L<D['blank_edge_threshold_m_inferred']").replace('[(1,2,4),(count-2,8,10),(count//2+1,4,6)]',"D['frame_groups'].get(str(ei),[])").replace('[(1,2,4,yellow),(count-2,8,10,yellow),(count//2+1,4,6,orange)]',"[(jj,ff,ee,[yellow,yellow,orange][kk]) for kk,(jj,ff,ee) in enumerate(D['frame_groups'].get(str(ei),[]))]")
 s=s.replace('[(.30,3),(.64,4),(.45,6),(.30,8),(.64,9)]','[(.30,round(FLOORS*.25)),(.64,round(FLOORS*.33)),(.45,round(FLOORS*.50)),(.30,round(FLOORS*.67)),(.64,round(FLOORS*.75))]')
 (P/'build.py').write_text(s)
 for name in ['check-standalone.py','check-entry.py','validate.py','check-frame-recess.py']:
  s=(O/name).read_text().replace('songpa-helio-city-416','songpa-helio-city-'+N).replace("'416동'",repr(N+'동')).replace("P.parent/'songpa-hellio", "P.parent.parent/'songpa-hellio")
  if name=='check-frame-recess.py':s=s.replace("pitch=D['body_height_m']/12","pitch=D['body_height_m']/D['floors']").replace('if L<16:continue',"if str(ei) not in D['frame_groups']:continue").replace('[(1,2,4),(count-2,8,10),(count//2+1,4,6)]',"D['frame_groups'][str(ei)]").replace("'source_storeys_preserved':12","'source_storeys_preserved':D['floors']")
  (P/name).write_text(s)
 (P/'README.md').write_text(f'Helio {N}: own exact source/register {H}m {F}F. Representative-photo-inference from416 v3; no individual facade photo claim. Own edge lengths classify slab ends (<16m) or branched returns (<12m), inferred rules. Frame groups retain two-storey size at own floor stations, never stretch whole representative mesh. Entry55% own shortwall inferred. Parcel479vs913 unresolved. Uniform no-child envelope assumption. Source/register number mesh is own{N}. No public/Git edits. Actual existing MCP9878 only.\n')
 print(N,H,F,'edges',len(r),'windowedges',len(groups),'entry',ei)
