import pathlib,json,hashlib,subprocess,sys
from PIL import Image
P=pathlib.Path(__file__).parent;sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();nums=list(map(int,sys.argv[1:]));rows=[]
for n in nums:
 q=P/str(n)
 for f in ['validate.py','check-entry.py','check-frame-recess.py']:subprocess.run([sys.executable,str(q/f)],check=True,stdout=subprocess.DEVNULL)
 D=json.loads((q/'source-data.json').read_text());V=json.loads((q/'geometry-proof.json').read_text());C=json.loads((q/'standalone-validation.json').read_text());assert json.loads(C['supersedesAssetIds'])==D['supersedesAssetIds'];glb=q/f'songpa-helio-city-{n}.glb';blend=q/f'songpa-helio-city-{n}-authored.blend';ims=[Image.open(q/(v+'.png')).convert('RGB') for v in ['front','opposite','side','roof']];canvas=Image.new('RGB',(1700,2200));[canvas.paste(im,(i%2*850,i//2*1100)) for i,im in enumerate(ims)];canvas.save(q/'review-four-views.png');rows.append({'assetId':f'bespoke-songpa-helio-city-{n}','tower':str(n),'footprintId':D['id'],'anchor_lonlat':D['anchor_lonlat'],'registerId':D['register_row']['id'],'registerHeightM':D['register_height_m'],'modeledUpperEnvelopeM':D['register_height_m'],'floors':D['floors'],'scope':D['reference_scope'],'heightAssumption':D['height_assumption'],'inferredFromAssetIds':D['inferredFromAssetIds'],'ancestorGlbSha256':D['ancestor_glb_sha256'],'supersedesAssetIds':D['supersedesAssetIds'],'glbPath':str(glb.relative_to(P)),'blendPath':str(blend.relative_to(P)),'sourceDataPath':str((q/'source-data.json').relative_to(P)),'regionsPath':str((q/'regions.json').relative_to(P)),'glbSha256':sha(glb),'blendSha256':sha(blend),'sourceSha256':sha(q/'source-data.json'),'glbBytes':glb.stat().st_size,'triangles':V['triangle_count'],'maximumSurfaceProjectionM':V['whole_surface_maximum_vertex_projection_m'],'status':'authored and validated; root review pending'})
for p,h in json.loads((P/'representative-preservation.json').read_text()).items():assert sha(pathlib.Path(p))==h
(P/f'bundle-{nums[0]}-{nums[-1]}.json').write_text(json.dumps(rows,indent=2));old=json.loads((P/'bundle.json').read_text()) if (P/'bundle.json').exists() else [];old=[r for r in old if int(r['tower']) not in nums];(P/'bundle.json').write_text(json.dumps(sorted(old+rows,key=lambda r:int(r['tower'])),indent=2));print([(r['tower'],r['glbBytes'],r['triangles']) for r in rows])
